### ISSUE TITLE
Don't urlencode post data

### ISSUE THREAD

**Issue by physikerwelt** [zbMATHOpen/Update_Links#7]
https://github.com/zbMATHOpen/Update_Links/blob/e4203575f53f8b32391b4c9bbffd988faef3b985/src/update_zblinks_api/update_with_api.py#L73-L74

See
https://www.w3schools.com/python/ref_requests_post.asp
how post requests work

**Comment by dehsani-academic** [comment]
couldn't get sth like requests.post(link_url, data=dict_input, headers=headers) to work, which is why urlencode was used.
still no success (again), but feel free to change it.

**Comment by physikerwelt** [comment]
ok. I'll have a look.

**Comment by physikerwelt** [comment]
ah you are right this is actually how the API is defined. Maybe the endpoint should become a get endpoint. The request generated by the swagger API has empty post data.

curl -X 'POST' \
  'https://zblink.formulasearchengine.com/links_api/link/item/?DE%20number=3273555&external%20id=%2011.14%23I1.i1.p1&partner=DLMF' \
  -H 'accept: application/json' \
  -d ''
